#!/bin/bash

echo "You need to create namespace if if does not exist"

kubectl delete -f mysql-pvc.yaml
kubectl delete -f matomo-pvc.yaml

sleep 15

echo "Create a PVC for matomo"
kubectl create -f matomo-pvc.yaml

echo "Create a PVC for mysql"
kubectl create -f mysql-pvc.yaml
echo "Waiting for mysql PVC to come up"
ready=""
while [ -z "$ready" ]; do
  sleep 6
  status=$(kubectl get pvc -n web-analytics | grep mysql)
  echo $status
  ready=$(echo "$status" | grep Bound)
done

echo "Data reset completed"



