---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: web-analytics
  labels:
    app: mysql
    tier: db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
    tier: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: web-analytics
  labels:
    app: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        tier: db
    spec:
      containers:
        - name: mysql
          image: notemaker/mysql:1.0
          imagePullPolicy: Always 
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pcIsSecure2

#              valueFrom:
#                secretKeyRef:
#                  name: passwords
#                  key: MYSQL_ROOT_PASSWORD 
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc


