#!/bin/bash
[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' to instruct which version to redeploy"

cd $1
echo; echo "Redeploying version $1 of Web Analytics application"
echo "Tearing down current deployment"
kubectl delete -f matomo.yaml
kubectl delete -f mysql.yaml
echo "Previous version deleted, wait for services to terminate"
sleep 10
cd ..

deploy $1


