#!/bin/bash

[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' and optionally mongo|note|perf" && exit 1

[ "$#" -eq 1 ] && op=mongonoteperf
[ "$#" -eq 2 ] && op=$2

echo; echo "Dploying version $1 of Note Maker application"
echo "Leveraging existing storage"

cd $1
[[ "$op" == *"mongo"* ]] && kubectl apply -f mongodb.yaml
sleep 10
[[ "$op" == *"note"* ]] && kubectl apply -f notemaker.yaml
[[ "$op" == *"perf"* ]] && kubectl apply -f performance-meter.yaml
sleep 10
cd ..





