#!/bin/bash

[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' and optionally matomo|mysql" && exit 1

# if no 2nd parameter passed in, deploy all
[ "$#" -eq 1 ] && op=matomomysql
[ "$#" -eq 2 ] && op=$2

echo; echo "Deploying version $1 of Note Maker application"
echo "Leveraging existing storage"

cd $1
[[ "$op" == *"matomo"* ]] && kubectl apply -f matomodb.yaml
sleep 10
[[ "$op" == *"mysql"* ]] && kubectl apply -f mysql.yaml
sleep 10
cd ..

echoPasswords




