#!/bin/bash
[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0'" && exit 1

kubectl create ns web-analytics
kubectl create -f data/secrets.yaml
kubectl create -f data/mysql-pvc.yaml
kubectl create -f data/matomo-pvc.yaml
sleep 20

deploy $1

