#!/bin/bash

[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' and optionally matomo|mysql" && exit 1

[ "$#" -eq 1 ] && op=matomomysql 
[ "$#" -eq 2 ] && op=$2

echo; echo "Redeploying version $1 of Web Analytics application"
echo "Leveraging existing storage"

cd $1
[[ "$op" == *"matomo"* ]] && kubectl delete -f matomo.yaml
[[ "$op" == *"mysql"* ]] && kubectl delete -f mysql.yaml
sleep 10
cd ..

deploy $@

