apiVersion: v1
kind: Service
metadata:
  name: monitor 
  namespace: notemaker
spec:
  selector:
    app: monitor
    tier: web 
  ports:
    - port: 80
      targetPort: 80 
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor 
  namespace: notemaker
  labels:
    app: monitor 
    tier: web 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor 
      tier: web 
  template:
    metadata:
      labels:
        app: monitor 
        tier: web 
    spec:
      containers:
        - name: monitor 
          image: monitorr/monitorr
          securityContext:
            privileged: true
          ports:
            - containerPort: 80 
          imagePullPolicy: Always

