#!/bin/bash

[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' and optionally mongo|web|perf" && exit 1


# if no 2nd parameter passed in, deploy all
[ "$#" -eq 1 ] && op=mongowebperf
[ "$#" -eq 2 ] && op=$2

echo "Deploying Notemaker on openshift using project 'notemaker'"
echo; echo "Deploying version $1 of Note Maker application"
echo "Leveraging existing storage"

cd $1
[[ "$op" == *"mongo"* ]] && kubectl apply -f mongodb.yaml
sleep 10
[[ "$op" == *"perf"* ]] && kubectl apply -f performance-meter.yaml
sleep 10

if [[ "$op" == *"web"* ]]; then
  kubectl apply -f web-service.yaml
  waitsvc web 
  ip=$(kubectl get svc -n notemaker | grep web-service | awk '{print $3}')
  echo "Use browser to create some notes at $ip" to generate runtime models"   
cd ..

