#!/bin/bash

echo "Make sure proper version of twistcli is in your PATH or add a full path below"
echo "For scanning user only needs CI Role; for API POST, operator or admin role"

export DEMO_BASE='<full path where the notemaker code resides>'
# SAMPLE:  export DEMO_BASE='/Users/<user>/git-repo-notemaker/notemaker-demo'

export PATH=$DEMO_BASE/scripts:./scripts:$PATH
export TL_USER='<some user>' > /dev/null
export TL_USER_PW='<user pw >' > /dev/null
export TL_CONSOLE='<console URL>' > /dev/null 
export TL_CONSOLE_API="$TL_CONSOLE/api/v1" > /dev/null

twistcli -version

echo "setup to use self hosted version of Prisma Cloud on $TL_CONSOLE"
echo "set environment variables TL_USER, TL_USER_PW, TL_CONSOLE_API, and TL_CONSOLE"


