#!/bin/bash

(( $# < 1 )) && \
  echo "Pass in a local image to scan and optionally twistcli image scan options." && \
  echo "Run 'scanImage --help' to see available scan options." && exit -1

[[ "$1" == "--help" ]] && twistcli images scan --help && exit 1

params=""
verbose=false
image="${@: -1}"

# params to twistcli includes image to scan as last one
if [ "$1" == '-v' ]; then
  params="${@:2}"
  verbose=true
else
  params="$@"
fi

   
# pass in v to get verbose print_msgs
print_msg() {
   [ "$verbose" == "true" ] && echo $1 
} 

print_msg "This only works with 20.04 hosted release and uses --ci flag"
print_msg "scan results saved on $TL_CONSOLE/#!/monitor/vulnerabilities/images/ci"

echo
echo "------------ Utilizing twistcli image scan to scan $image --------------"
result=$(twistcli images scan -u $TL_USER -p $TL_USER_PW --address $TL_CONSOLE \
   --ci $params | grep -v DATA)

printf "%s\n" "$result"

result=$(echo $result | grep -c "Scan failed due to")

echo "------------------ twistcli scan of $images complete --------------------"
exit $result

