#!/bin/bash

echo "Make sure proper version of twistcli is in your PATH or add a full path below"
echo "For scanning user only needs CI Role; for API POST, operator or admin role"

export DEMO_BASE='/Users/mbarker/git-repo-notemaker/notemaker-demo'
export PATH=$DEMO_BASE/scripts:./scripts:$PATH
export TL_USER='operator' > /dev/null
export TL_USER_PW='operator4u' > /dev/null
export TL_CONSOLE='https://35.184.86.115:8083' > /dev/null 
export TL_CONSOLE_API="$TL_CONSOLE/api/v1" > /dev/null

read -p "Do you want to download the latest version of twistcli(y/n)? " -n 1 -r
echo
[[ $REPLY =~ [Yy]$ ]] && download-twistcli

twistcli -version

echo "setup to use self hosted version of Prisma Cloud on $TL_CONSOLE"
echo "set environment variables TL_USER, TL_USER_PW, TL_CONSOLE_API, and TL_CONSOLE"


