apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: web-analytics
spec:
  ports:
  - port: 3306
  selector:
    name: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: web-analytics
spec:
  selector:
    matchLabels:
      name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql 
        image: notemaker/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: PrismaIsSecure2xyyZ 
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
#          subPath: "mysql"
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

